// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/haya14busa/reviewdog/cmd/reviewdog"
	_ "github.com/kisielk/errcheck"
	_ "github.com/srvc/wraperr/cmd/wraperr"
	_ "golang.org/x/lint/golint"
	_ "honnef.co/go/tools/cmd/megacheck"
	_ "mvdan.cc/unparam"
)
